name: zycloud_client
description: Dart network client library for ZyCloud service.
version: 1.0.2
repository: https://github.com/yangfanyu/zycloud_client

topics:
  - client
  - zycloud
  - codepush

environment:
  sdk: ^3.0.0

dependencies:  
  http: ^1.1.0
  lpinyin: ^2.0.0
  shelf_easy: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
