name: zycloud_client
description: This library includes interfaces such as user module, administrator module, real-time chat module, custom data module, and Dart code push hosting module.
version: 2.0.1
repository: https://github.com/yangfanyu/zycloud_client

topics:
  - client
  - zycloud
  - codepush

environment:
  sdk: ^3.0.0

dependencies:  
  http: ^1.1.0
  lpinyin: ^2.0.0
  shelf_easy: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
